### ISSUE TITLE
contracts/KyberContirbutorWhitelist.sol

### ISSUE THREAD

**Issue by insou22** [KyberNetwork/TokenDistributionContracts#1]
contracts/KyberContirbutorWhitelist.sol

should be spelled: contracts/KyberContributorWhitelist.sol

**Comment by yaronvel** [comment]
Fixed in this [commit](https://github.com/KyberNetwork/TokenDistributionContracts/commit/3023673dc54a6bf4426ed0814f9652d5586f6c07)

Thanks,
