### ISSUE TITLE
finalizeSale should be callable by everyone but requires admin sender

### ISSUE THREAD

**Issue by Montoya** [KyberNetwork/TokenDistributionContracts#3]
```
    event FinalizeSale();
    // function is callable by everyone
    function finalizeSale() {
        require( saleEnded() );
        require( msg.sender == admin );
```

It would make sense to allow anyone to call `finalizeSale` once the sale has ended, in case the admin is not available for any reason, but this function still requires `msg.sender==admin`.

**Comment by yaronvel** [comment]
We consider it. But decided not to. We will first verify user didnt send tokens to the contract by mistake and only then burn the remaining tokens.
It is true that in theory tokens are not tranferable till end of token sale. But still, we decided to be extra careful.
The down side is that a trust is now needed. But in token sale a trust in the issuer is needed anyway.
