### ISSUE TITLE
Is leftover KNC from whitelist available for public crowd?

### ISSUE THREAD

**Issue by ieow** [KyberNetwork/TokenDistributionContracts#4]
Although it might not possible, there might be left over KNC from whiltelist due to whatever reason.
It the leftover open for public?
Do not saw any code which allows that.

**Comment by yaronvel** [comment]
Left overs after 48 hours sale are burned

**Comment by ieow** [comment]
I mean leftover after the openSaleStartTime. Is there a public 'openSale' ?
The code below will disallow public sales since all contributor coming in after `openSaleStartTime` also need to be checked with `contributorCap' .

in ContributorApprover.sol
`
    function eligible( address contributor, uint amountInWei ) constant returns(uint) {
        if( now < cappedSaleStartTime ) return 0;
        if( now >= openSaleEndTime ) return 0;

        uint cap = contributorCap( contributor );

        if( cap == 0 ) return 0;
        if( now < openSaleStartTime ) {
            uint remainedCap = cap.sub( participated[ contributor ] );

            if( remainedCap > amountInWei ) return amountInWei;
            else return remainedCap;
        }
        else {
            return amountInWei;
        }
}
`

**Comment by yaronvel** [comment]
Even in open sale, only whitelisted users can participate. If your cap is 0, you are not whitelisted, and you cannot join.

**Comment by ieow** [comment]
so who can join participate in opensale?
whitelisted who is yet contributed?
if that the case, there is no need opensale

**Comment by ieow** [comment]
if i am whitelisted, I could just wait after `openSaleStartTime` and try to buy any amount is remained.
not fair to other whitelisted

**Comment by yaronvel** [comment]
Any whitelist user. In capped sale your are limited by a cap. In open sale only hard cap is the limit.

**Comment by yaronvel** [comment]
Any user can participate in both periods

**Comment by ieow** [comment]
If I participated in cappedsales and no more cap, i cant join open sales.
But if I skip cappedsales, I can contribute any cap remain in open sales

**Comment by ieow** [comment]
Shouldn't the code should be like this?
`
    if( now < openSaleStartTime ) {
        uint cap = contributorCap( contributor );

        if( cap == 0 ) return 0;
        uint remainedCap = cap.sub( participated[ contributor ] );

        if( remainedCap > amountInWei ) return amountInWei;
        else return remainedCap;
    }
    else if (token.amount_remain > amountInWei){
        return amountInWei;
    }
`

**Comment by yaronvel** [comment]
I think there is a misunderstanding.
Use can (and should) participate both in capped and open sale. In the capped sale duration, he can buy only according to his cap. After that he can buy with any amount (as long as there are enough tokens for sale).

**Comment by ieow** [comment]
Yes, I understand user should able to participate both in capped and open sale even they contributed max cap during the capped sale.

But the code 

`
        uint cap = contributorCap( contributor );
        if( cap == 0 ) return 0;
`
will always return 0 for user who contributed max cap during the capped session.
But it was not the case for user who did not contributed max cap during the capped session.

**Comment by ieow** [comment]
@loiluu

**Comment by yaronvel** [comment]
`contributorCap( contributor )` is only the cap. The return value is not changing after making a contribution.
What is changing after contribution is `participated` value.

**Comment by ieow** [comment]
so, after the `openSaleStartTime`, the amount eligible do not need to check with remaining token?

**Comment by hh3755** [comment]
@ieow `SafeMath` will not allow you do that,see the source code.Then only thing will happen is sold out, never over sold.

```
  function sub(uint256 a, uint256 b) internal constant returns (uint256) {
    assert(b <= a);
    return a - b;
  }
```

**Comment by ieow** [comment]
cap.sub is only called during the capped session but not the open sale session
```
        if( now < openSaleStartTime ) { 
            uint remainedCap = cap.sub( participated[ contributor ] );
            if( remainedCap > amountInWei ) return amountInWei;
            else return remainedCap;
        }
        else {
            return amountInWei;
       }
```

**Comment by yaronvel** [comment]
>That mean any whitelist can buy in any amount after openSaleStartTime

From `eligible` function point of view, yes.
But if there are not enough tokens left, `transfer` function will `throw` and everything is reverted. So it is not possible to buy more tokens than there are in supply.

You might notice some asymmetry here. In capped sale, if you buy more than your cap, we execute the sale and give you a change back. While in open sell we just throw if there are not enough tokens. Reason is the `buy` function allows anyone to buy on behalf of a white-listed address, hence we must handle the case where cap is exceeded by some epsilon, in order to ensure fairness.
While in the general uncapped case, it is only an edge case that might prevent you from buying some remaining epsilon (buy your personal cap is still guaranteed).
This is common in many token sale contracts. Reason is that from UX point of view, users might be confused to see that their tx didn't throw and still they only got partial return.

**Comment by ieow** [comment]
Understood. No more comment on this.

**Comment by yaronvel** [comment]
thanks for the feedback

**Comment by ieow** [comment]
Thanks for explaining. I am still learning. :)
