### ISSUE TITLE
The exchange rate of KNC should be marked as a constant?

### ISSUE THREAD

**Issue by hh3755** [KyberNetwork/TokenDistributionContracts#5]
May the exchange rate of KNC from ETH be a constant? Or did any document which suggest the exchange rate.

https://github.com/KyberNetwork/TokenDistributionContracts/blob/5f9744a3e1647728c69d0fbb3c7605f313faba94/TokenSale/contracts/KyberNetworkTokenSale.sol#L80

**Comment by yaronvel** [comment]
It is constant during the sale
