### ISSUE TITLE
Transferable after T+9

### ISSUE THREAD

**Issue by ieow** [KyberNetwork/TokenDistributionContracts#6]
Is  `&& now >= saleStartTime` needed to check the transferable ?
Since it is enforcing transferable can be made by contract only before T+ 9,  wouldn't `now <= saleEndTime ` is enough and provide more security since it only allow transferable by contract only before T+9 instead of between T and T+9

btw, although it is insignificant, it could reduce gas.
```
    modifier onlyWhenTransferEnabled() {
        if( now <= saleEndTime && now >= saleStartTime ) {
            require( msg.sender == tokenSaleContract );
        }
        _;
}
```

**Comment by yaronvel** [comment]
We want to do it in order to manually check token transfers before sale starts. Just to gain extra confident. As describe in our readme file, after deployment we will transfer few of company tokens just to see that everything is a alive.

**Comment by ieow** [comment]
I see. Thanks for explaining.
Good to know that there are checking transfer before sale starts.
