### ISSUE TITLE
NetworkCrystal.sol: L70

### ISSUE THREAD

**Issue by GoldenDave** [KyberNetwork/TokenDistributionContracts#7]
```
    // save some gas by making only one contract call
    function burnFrom(address _from, uint256 _value) onlyWhenTransferEnabled
        returns (bool) {
        assert( transferFrom( _from, msg.sender, _value ) );
        return burn(_value);
    }
```

making an assert is pointless - transferFrom can only return true.
Kinda goes against the point of saving gas....

**Comment by yaronvel** [comment]
yes, but gas costs here are negligible.
Using `onlyWhenTransferEnabled` is also not needed, as it is checked both by `burn` and `transferFrom`.
Still, external contract call, is at least one order of magnitude more expensive than checking simple boolean conditions.

**Comment by DaveAppleton** [comment]
Yeah I know :-)
 - and the new standard insists that we MUST check returns.

**Comment by yaronvel** [comment]
Yeah, standards are not fun.
Safe math is the worse thing ever happened.
Also, after taking away `throw`, replacing `send` with `transfer`, now it is also not ok to use `now` in your code.
