### ISSUE TITLE
Short Address Attack is not covered

### ISSUE THREAD

**Issue by midinpa** [KyberNetwork/TokenDistributionContracts#8]
`function transfer(address _to, uint256 _value) returns (bool) {
    balances[msg.sender] = balances[msg.sender].sub(_value);
    balances[_to] = balances[_to].add(_value);
    Transfer(msg.sender, _to, _value);
    return true;
  }`
As you may know, attackers can use short address attack by sending less data intensively, and EVM will fill the missing bytes with zeros which can cause problems transferring tokens.

Payload size needs to be checked in transfer function like below (also transferFrom in the same way). 
Subcontract function (using this transfer and transferFrom function) is not receiving fewer arguments, so the onlyPayloadSize check will not fail.

`modifier onlyPayloadSize(uint size) {
    assert(msg.data.length >= size + 4);
    _;
  }`
` function transfer(address _to, uint256 _value) onlyPayloadSize(2 * 32) returns (bool) {
    balances[msg.sender] = balances[msg.sender].sub(_value);
    balances[_to] = balances[_to].add(_value);
    Transfer(msg.sender, _to, _value);
    return true;
}`

**Comment by yaronvel** [comment]
The mitigation has known [issues](https://blog.coinfabrik.com/smart-contract-short-address-attack-mitigation-failure/).
It is no longer a standard. Open zeppelin for example decided to remove it.
Hence, we also do not apply it.
