### ISSUE TITLE
Possible Re-entrancy Attack

### ISSUE THREAD

**Issue by Everhusk** [KyberNetwork/TokenDistributionContracts#9]
Hi,

I was just looking over your code and I believe this line may make it vulnerable to a re-entrancy attack:

https://github.com/KyberNetwork/TokenDistributionContracts/blob/master/TokenSale/contracts/KyberNetworkTokenSale.sol#L74

Thankfully, it shouldn't be possible to drain the contract because it looks like it immediately transfers any ether to your multisig. Wanted to raise the issue just in case something weird happens. Best of luck with the sale!

Cheers

**Comment by yaronvel** [comment]
`transfer` is not vulnerable to re-entracy attack as it gives 2k gas limit to the external call, which is not sufficient to any storage update.
`msg.sender.call()` would have enabled re-entry. But this is not the case here.
